#!/bin/bash

docker run -d --name overlord --restart=always nginx -p $(docker-machine ip Char):5000:80


#Launch annginxcontainer, available on Docker Hub, as a background task.
# Itshould be namedoverlord, be able to restart on its own, and have its 80 portattached to the 5000 port ofChar.
# You can check that your container functionsproperly by visitinghttp://<ip-de-char>:5000on your web browser.