#!/bin/bash

# docker service ps engineering-bay
# docker service inspect -f "{{.Spec.TaskTemplate.ContainerSpec.Env}}" engineering-bay

docker service create --network overmind --replicas 2 --name engineering-bay -e OC_USERNAME=user -e OC_PASSWD=pass 42school/engineering-bay


#Launch a 42school/engineering-bay service in two replicas and make sure that
# the service works properly (see the documentation provided at hub.docker.com).
# This service will be named engineering-bay and will be on the overmind network.