#!/bin/bash

# docker service ps marines
# docker service inspect -f "{{.Spec.TaskTemplate.ContainerSpec.Env}}" marines
# docker service logs marines

docker service create --network overmind --replicas 2 --name marines -e OC_USERNAME=user -e OC_PASSWD=pass 42school/marine-squad

#... Damn it, a group of zergs is attacking orbital-command, and shutting down
# the engineering-bay service won’t help at all... You must send a troup of Marines
# to eliminate the intruders. Launch a 42school/marine-squad in two replicas,
# and make sure that the service works properly (see the documentation provided
# at hub.docker.com). This service will be named... marines and will be on the
# overmind network.