FROM alpine

RUN apk update && apk add vim;

ENTRYPOINT ["vim"]

#From an alpine image you’ll add to your container your favorite text editor, vim or
# emacs, that will launch along with your container.